#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require "vendor/autoload.php";

$app = new Application('Task Application', '1.0');

try {
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Exeption $e) {
    echo "Could not connect to database --->>> " . $e->getMessage();
    exit(1);
}

$dbAdapter = new Acme\DatabaseAdapter($pdo);

$app->add(new Acme\ShowCommand($dbAdapter));
$app->add(new Acme\AddCommand($dbAdapter));
$app->add(new Acme\DeleteCommand($dbAdapter));

$app->run();